if(NOT DEFINED README_FILE)
  message(FATAL_ERROR "README_FILE is required")
endif()

file(READ "${README_FILE}" README_CONTENT)
foreach(FORBIDDEN_PREFIX IN ITEMS "/home/" "/Users/")
  string(FIND "${README_CONTENT}" "${FORBIDDEN_PREFIX}" PREFIX_OFFSET)
  if(NOT PREFIX_OFFSET EQUAL -1)
    message(FATAL_ERROR
      "README contains machine-specific path prefix: ${FORBIDDEN_PREFIX}")
  endif()
endforeach()

function(require_readme_text required_text)
  string(FIND "${README_CONTENT}" "${required_text}" required_offset)
  if(required_offset EQUAL -1)
    message(FATAL_ERROR "README is missing required text: ${required_text}")
  endif()
endfunction()

require_readme_text("mkdir -p benchmark_results/pico_live/traces")
require_readme_text("--pico-record benchmark_results/pico_live/traces/output_continuity_retest.tjvr")
require_readme_text("TRACE_FILE=benchmark_results/pico_live/traces/output_continuity_retest.tjvr")
require_readme_text("test -f \"$TRACE_FILE\" ||")
require_readme_text("--input \"$TRACE_FILE\"")
require_readme_text("回放模型：`models/marvin_m6_qp_pico_fast.xml`")
require_readme_text("回放状态源：`model_reference`")
